version: "3"

vars:
  BROWSER_NAME: "Brave Browser"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task -l --sort none

  run:
    desc: Run go program
    cmds:
      - go run ./...

  fmt:
    desc: Format go program
    cmds:
      - go fmt ./...

  vet:
    desc: Doctor go program
    cmds:
      - go vet ./...

  test:
    desc: Test go program
    cmds:
      - go test ./...

  dev:title:
    desc: Get browser title for debug
    cmds:
      - open "{{.URL}}"
      - sleep 2
      - |
        osascript -e 'tell application "{{.BROWSER_NAME}}" to get title of active tab of front window' | \
          tee /dev/tty | \
          pbcopy
    requires:
      vars: [URL]
