version: "3"

dotenv: [ ".env" ]

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task -l --sort none

  build:
    desc: Build go program
    cmds:
      - go build -o copy-tab-link ./cmd

  run:
    desc: Run go program
    cmds:
      - go run ./... -browser-name="{{.BROWSER_NAME}}"
    vars:
      BROWSER_NAME: '{{.BROWSER_NAME | default "$BROWSER_NAME"}}'

  fmt:
    desc: Format go program
    cmds:
      - go fmt ./...

  vet:
    desc: Doctor go program
    cmds:
      - go vet ./...

  test:
    desc: Test all case
    cmds:
      - go test -v ./...

  test:run:
    desc: Test specific case
    cmds:
      - go test -v -run "{{.NAME}}" ./...
    requires:
      vars: [ NAME ]

  dev:title:
    desc: Get browser title for debug
    cmds:
      - open -a "$BROWSER_NAME" "{{.URL}}"
      - sleep 2
      - |
        osascript -e "tell application \"$BROWSER_NAME\" to get title of active tab of front window" | \
          tee /dev/tty | \
          pbcopy
    requires:
      vars: [ URL ]
